server:
  port: 8000

spring:
  datasource:
    username: root
    #password: Mmza6537###
    password: Ast4HS
    url: jdbc:mysql://localhost:3306/czlDemo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    connect-timeout: 1000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: mmza6537...
    listener:
      direct:
        acknowledge-mode: manual
    virtual-host: /


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      #删除后
      logic-delete-value: 0